apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE}
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: DB_URL
              value: ${DB_URL}
            - name: DB_USERNAME
              value: ${DB_USERNAME}
            - name: DB_PASSWORD
              value: ${DB_PASSWORD}
            - name: ENCRYPTION_SECRET_KEY
              value: ${ENCRYPTION_SECRET_KEY}
            - name: JWT_SECRET_ACCESS
              value: ${JWT_SECRET_ACCESS}
            - name: JWT_SECRET_REFRESH
              value: ${JWT_SECRET_REFRESH}
          image: ${IMAGE}
          ports:
            - containerPort: 8080
              name: http1
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi

