spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: postgresql
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: mayb

springdoc:
  packages-to-scan: kr.mayb.controller
  api-docs:
    path: /docs
    groups.enabled: false
  swagger-ui:
    path: /docs/ui
    display-operation-id: true
    syntax-highlight.theme: monokai
    doc-expansion: none

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY}

jwt:
  secret:
    access: ${JWT_SECRET_ACCESS}
    refresh: ${JWT_SECRET_REFRESH}
