---
# interface application config

spring.application.name: mayb-api
spring:
  profiles:
    active: ${zone:local}
    group:
      "local": local,common
      "dev": dev,common
      "prod": common

---
# local config
spring.config.activate.on-profile: local

---
# dev config
spring.config.activate.on-profile: dev

---
# prod config
spring.config.activate.on-profile: prod