---
# interface application config

spring.application.name: mayb-api
spring.profiles.active: ${zone:dev}

logging.level:
  org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver: error
  org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: error
  org.springframework.web.servlet.mvc.annotation.ResponseStatusExceptionResolver: error

  org.apache.pdfbox: error
  org.apache.fontbox: error

server.compression.enabled: true

spring.mvc.pathmatch.matching-strategy: ant-path-matcher
spring.sleuth.sampler.probability: 0.1

springdoc:
  packages-to-scan: kr.mayb.app.controller
  api-docs:
    path: /docs
    groups.enabled: false
  swagger-ui:
    path: /docs/ui
    display-operation-id: true
    syntax-highlight.theme: monokai
    doc-expansion: none

---
# dev config
spring.config.activate.on-profile: dev

---
# prod config
spring.config.activate.on-profile: prod